import { Icon } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { LogoWhite } from "../assets/icons";
import Share from "../components/share";

import styles from "../styles/Home.module.scss";
import { useEffect, useRef } from "react";
import WaitingScreen from "../screens/waiting";
import OverviewScreen from "../screens/overview";
import ControlPage from "../components/control-page";

const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>King playing in the space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}>
         <WaitingScreen show={false}/>
      </main> */}
      <main id="main">
        
        <OverviewScreen/>
        <ControlPage/>
      </main>
    </div>
  );
};

export default Home;
